# Question 1:	
You are given a big matrix and a smaller one, write a function that returns the coordinates of a smaller matrix within a bigger one. Start with 2d and experiment with higher dimensions. 

NumPy has universal functions (ufuncs) that operates on the ndarray object. Rather than iterating through arrays, use ufuncs to implement vectorization (i.e. convert iterative statementsinto a vector based operation). 

The zip method:

In [84]:
#THIS matches the first number of the little matrix everywhere it appears. A lot more work is needed to make this better. Skip to below.
# import numpy as np

# #2x3 matrix
# bigMatrix = np.array([[1, 2, 3], [4, 5, 6], [4, 6, 7], [2, 6, 6]])
# print(bigMatrix) #matrix A
# # Useful to check size and shape of array for further calculations
# # print("number of dimensions: ", bigMatrix.ndim) 
# # print("Shape rows, columns: ", bigMatrix.shape) 
# # print("View number of elements (rows * columns): ", bigMatrix.size) 
# # print("First row bigMatrix[0] = ", bigMatrix[0]) 
# # print("Second row bigMatrix[1] = ", bigMatrix[1]) 

# #2 x 2 matrix
# smallMatrix = np.array([[2, 3], [5, 6]]) 
# print(smallMatrix)

# def match_first_coordinate(smallMatrix, bigMatrix):
#   print(smallMatrix.shape) # (2, 2)
#   #smallMatrix x and y 
#   x = 0
#   y = 0
#   #iterate over list of bigMatrix coordinates and print them where the values match the smallMatrix
#   result = np.where(bigMatrix == smallMatrix[x, y]) #returns tuple of arrays (array([row_indeces]), array([column_indeces])).
#   #Both arrays have the same length and can therefore be zipped so that the item at the same index of each array is paired e.g. (first_row, first_column).
#   #This will return key value pairs i.e. coordinates
#   listOfCoordinates = list(zip(result[0], result[1])) #returns coordinates [row_index, column_index]
#   print('The top left corner of the small matrix is at big matrix coordinate: ', listOfCoordinates)
#   for cord in listOfCoordinates:
#     print(cord)


# match_first_coordinate(smallMatrix, bigMatrix)

#

In [85]:
#Where: find first coordinate that matches 
#slice: that matrix
import numpy as np

#2Dimensionsal
bigMatrix = np.array([[2, 2, 3, 8], [4, 5, 6, 8], [4, 6, 7, 8], [2, 6, 6, 8]])
print(bigMatrix) 
smallMatrix = np.array([[2, 3, 8], [5, 6, 8]]) 
print(smallMatrix)
smallMatrix2 = np.array([[6, 8], [7, 8], [6, 8]]) 

class MatrixSearch:
  #match first coordinate
  #@staticmethod #Static method knows nothing about the class and just deals with the parameters. Static methods, much like class methods, are methods that are bound to a class rather than its object.
  def match_coordinates(smallMatrix, bigMatrix):
    smallMatrix_shape = smallMatrix.shape #returns dimensions of matrix shape row x column for 2D
    print("SmallMatrix shape is ", smallMatrix_shape)
    width = smallMatrix_shape[0]
    height = smallMatrix_shape[1]
    print("This is height: ", height)
    print("This is width: ", width)   
    result = np.where(bigMatrix == smallMatrix[0, 0]) 
    #Finds first coordiante ie match top left corner of small matrix
    for i in range(len(result)):
      x = result[i][0] #column
      y = result[i][1] #row
      print("This is x ", x)
      print("This is y ", y)
      #This slices the little matrix out of the bigmatrix 
      search_matrix = bigMatrix[x: x + width, y: y + height] 
      print(search_matrix)
      if np.array_equal(smallMatrix, search_matrix):
        match = [x, y]
        print("Match found starting at coordinate: ", match)
        return match #should return all matching coordinates. Stops searching after finding first match.
    return None
  
  #@staticmethod
  def show_all_coordinates(smallMatrix, bigMatrix, match):
    smallMatrix_shape = smallMatrix.shape #returns dimensions of matrix shape row x column for 2D
    height = smallMatrix_shape[0]
    width = smallMatrix_shape[1]
    matches = []
    x = match[0]
    y = match[1]
    for dy in range(y, y + height):
      for dx in range(x, x + width):
          matches.append([dx, dy])
    return matches

match = MatrixSearch.match_coordinates(smallMatrix2, bigMatrix)
if match == None:
  print("bigMatrix searched but smallMatrix not found")
else:
  print(MatrixSearch.show_all_coordinates(smallMatrix2, bigMatrix, match))


[[2 2 3 8]
 [4 5 6 8]
 [4 6 7 8]
 [2 6 6 8]]
[[2 3 8]
 [5 6 8]]
SmallMatrix shape is  (3, 2)
This is height:  2
This is width:  3
This is x  1
This is y  2
[[6 8]
 [7 8]
 [6 8]]
Match found starting at coordinate:  [1, 2]


In [86]:
# #3 dimensional solution
# import numpy as np

# #2Dimensionsal
# # bigMatrix = np.array([[1, 2, 3], [4, 5, 6], [4, 6, 7], [2, 6, 6]])
# # print(bigMatrix) 
# # smallMatrix = np.array([[2, 3], [5, 6]]) 
# # print(smallMatrix)
# # print(bigMatrix) 
# # smallMatrix = np.array([[2, 3], [5, 6]]) 
# # print(smallMatrix)
# ##3D: 2x3x4
# bigMatrix = np.array(
#   [
#     [
#       [1, 2, 3],
#       [4, 5, 6], 
#       [4, 6, 7], 
#       [2, 6, 6]
#     ],

#     [
#       [10, 20, 30],
#       [40, 50, 60], 
#       [40, 60, 70], 
#       [20, 60, 60]
#     ]
#   ]
# )
# print(bigMatrix) 
# smallMatrix = np.array(
#   [
#     [
#       [2, 3],
#       [5, 6]
#     ],

#     [
#       [20, 30],
#       [50, 60]
#     ]
#   ]
#   ) 

# print(smallMatrix)

# def match_coordinates(smallMatrix, bigMatrix):
#   smallMatrix_shape = smallMatrix.shape #returns dimensions of matrix shape row x column for 2D
#   height = smallMatrix_shape[0]
#   width = smallMatrix_shape[1]
#   depth = smallMatrix_shape[2]
#   print("SmallMatrix shape is ", smallMatrix_shape)
#   result = np.where(bigMatrix == smallMatrix[0, 0, 0]) 
#   matches_x = [] 
#   matches_y = []
#   matches_z = []
#   matches = []
#   #Finds first coordiante ie match top left corner of small matrix
#   print(result)
#   for i in range(len(result[0])):
#     x = result[i][0]
#     y = result[i][1]
#     z = result[i][2]
#     print("This is x ", x)
#     print("This is y ", y)
#     print("This is z ", z)
#     #This slices the little matrix out of the bigmatrix 
#     search_matrix = bigMatrix[y: y + height, x: x + width, z: z + depth] 
#     print(search_matrix)
#     if np.array_equal(smallMatrix, search_matrix):
#       matches_x.append(x)
#       matches_y.append(y)
#       matches_z.append(z)
#       for dx in range(x, x + width):
#          for dy in range(y, y + height):
#            for dz in range(z, z + depth):
#             matches.append([dy, dx, dz])
#       # print(matches_x)
#       # print(matches_x)
#       print("Print matches: ", matches)
#       return matches #should return all matching coordinates. Stops searching after finding first match.
#   return

# match_coordinates(smallMatrix, bigMatrix)

# # TO DO:
# # Tweak 3D to get it working

##### References

- https://thispointer.com/find-the-index-of-a-value-in-numpy-array/
- https://www.w3schools.com/python/numpy/numpy_array_iterating.asp
- https://www.w3schools.com/python/numpy/numpy_ufunc.asp
- https://numpy.org/doc/stable/index.html
- https://www.programiz.com/python-programming/methods/built-in/classmethod 
  The difference between a static method and a class method is:
  a) Static method knows nothing about the class and just deals with the parameters
  b) Class method works with the class since its parameter is always the class itself.
  see also: https://www.programiz.com/python-programming/methods/built-in/staticmethod