# Question 1.	
You are given a big matrix and a smaller one, write a function that returns the coordinates of a smaller matrix within a bigger one. Start with 2d and experiment with higher dimensions.

In [33]:
import numpy as np 

# find match by row/column index
# iterate through A row 1. return coordinates for matches with B
# Row 2 use same column for row to and confirm match.return coordinates.

#2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) #matix A
# Useful to check size and shape of array for further calculations
print("number of dimensions: ", A.ndim) 
print("Shape rows, columns: ", A.shape) 
print("View number of elements (rows * columns): ", A.size) 
print("First row A[0] = ", A[0]) 
print("Second row A[1] = ", A[1]) 

#2 x 2 matrix
B = np.array([[2, 3], [5, 6]]) 
print(B) 

# Iterate on each scalar element of the 2-D "A" array
for x in A:
  for y in x:
    print(y) 

i = 0
while A[i] < A.size:
    print(A[i])
    i = i+1
    if(i==A.size):
        break


#in each column 
#np.function(A, axis=0) 
#in each row 
#(B, axis=1) 

#row = x 
#x += 1 

[[1 2 3]
 [4 5 6]]
number of dimensions:  2
Shape rows, columns:  (2, 3)
View number of elements (rows * columns):  6
First row A[0] =  [1 2 3]
Second row A[1] =  [4 5 6]
[[2 3]
 [5 6]]
1
2
3
4
5
6
