# Question 1:	
You are given a big matrix and a smaller one, write a function that returns the coordinates of a smaller matrix within a bigger one. Start with 2d and experiment with higher dimensions.

NumPy has universal functions (ufuncs) that operates on the ndarray object. Rather than iterating through arrays, use ufuncs to implement vectorization (i.e. convert iterative statementsinto a vector based operation). 

The zip method:

In [34]:
import numpy as np

#2x3 matrix
bigMatrix = np.array([[1, 2, 3], [4, 5, 6]])
print(A) #matrix A
# Useful to check size and shape of array for further calculations
# print("number of dimensions: ", A.ndim) 
# print("Shape rows, columns: ", A.shape) 
# print("View number of elements (rows * columns): ", A.size) 
# print("First row A[0] = ", A[0]) 
# print("Second row A[1] = ", A[1]) 

#2 x 2 matrix
smallMatrix = np.array([[2, 3], [5, 6]]) 
print(B)

def match_first_coordinate(smallMatrix, bigMatrix):
#iterate over list of bigMatrix coordinates and print them where the values match the smallMatrix
  result = np.where(bigMatrix == smallMatrix[0,0]) #returns tuple of arrays (array([row_indeces]), array([column_indeces])).
  #Both arrays have the same length and can therefore be zipped so that the item at the same index of each array is paired e.g. (first_row, first_column).
  #This will return key value pairs i.e. coordinates
  listOfCoordinates = list(zip(result[0], result[1])) #returns coordinates [row_index, column_index]
  print('The top left corner of the small matrix is at big matrix coordinate: ', listOfCoordinates)
  for cord in listOfCoordinates:
      print(cord)

match_first_coordinate(smallMatrix, bigMatrix)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
The top left corner of the small matrix is at big matrix coordinate:  [(0, 1)]
(0, 1)


extract
where

##### References

- https://thispointer.com/find-the-index-of-a-value-in-numpy-array/
- https://www.w3schools.com/python/numpy/numpy_array_iterating.asp
