# Question 1:	
You are given a big matrix and a smaller one, write a function that returns the coordinates of a smaller matrix within a bigger one. Start with 2d and experiment with higher dimensions.

In [22]:
import numpy as np 

# find match by row/column index
# iterate through A row 1. return coordinates for matches with B
# Row 2 use same column for row to and confirm match.return coordinates.

# helper function, given an x,y coordinate , it returns true or false whether match.
# given a coordinate, is the smaller matrix at this location
# loop through all coordinates
# 1) loop through all coordinates
# 2) is the small matrix at the coordinate -> true or false [HELPER FUNCTION]

# LOOP THROUGH ALL BIG MATRIX COORDINATES 
def check_matrix_coordinates(smallmatrix, bigmatrix):
  #matrix.shape gives in 2D [row, column], in 3D [row, column, depth]
  bigwidth = bigmatrix.shape[0]  # bigmatrix width aka number of rows
  bigheight = bigmatrix.shape[1] # bigmatrix height aka number of columns
  matrixfound = False
  for x in range(bigwidth): #for each element in the big matrix x axis [0 ...bigwidth] 
      for y in range(bigheight): #for each element in the big matrix y axis [0 ...bigheight] 
        coordinate = [x, y] #check this coordinate x,y
        #testing 
        if is_matrix_at_coordinate(coordinate, smallmatrix, bigmatrix):
          print("The top left corner of the little matrix in the big matrix is at: ", coordinate) #the coordinate where the matrix starts ie the top left corner of small matrix at index [0,0]
          # BUILD UP ARRAY OF ALL COORDINATES & return that ##########################          
          matrixfound = True 
  if not matrixfound: 
    print("Matrix not found")      

# HELPER FUNCTION: given an x,y coordinate, look for match and return true or false
# Parameter (1) The coordinate is the top left corner of the small matrix as located in the big matrix. ie hitting the front of the battleship
# Parameter (2) The smallmatrix: x by y dimensions containing specific elements
# Parameter (3) The bigmatrix: The grid/ ocean
# Returns true if the entire small matrix is found within the bigmatrix starting at coordinate location.
def is_matrix_at_coordinate(coordinate, smallmatrix, bigmatrix): 
  #loop starting at coordinate location of each item in the big matrix, compare to item in small matrix & check if items equal
  
  #[x, y] x is at the 0 index, y is at the 1 index 
  x = coordinate[0] #this row
  y = coordinate[1] #this column
  #matrix.shape gives in 2D [row, column], in 3D [row, column, depth]
  smallwidth = smallmatrix.shape[0]         
          #smalldepth = .....[3] for a 3d array print("smallwidth = ", smallwidth)
  smallheight = smallmatrix.shape[1]        
  bigwidth = bigmatrix.shape[0]            
  bigheight = bigmatrix.shape[1]           
          #bigdepth = ....[3] for 3d array
          #For multi dimensional arrays - The nesting of the number of loops would be defined by the number dimensions of the matrix. 

  #MAKE SURE THE SMALL MATRIX COORDINATE (the location of the top left corner of the small matrix aka hit battleship on the nose) 
   #IS WITHIN DIMENSIONS OF THE BIG MATRIX (don't search outside the big matrix - the shot must be in the ocean in the ocean)
      #The first item in the matrix is 0,0 (negatives fall outside the matrix so no need to test there)
        #only test the coordinates within the matrix
  if x < 0: # matrix starts at coordinate index 0, so there is no coordinate below zero
    return False
  if x >= bigwidth: # number items on x axis in big matrix. Indexing starts at zero, so number of items -1
    return False
  if y < 0: # matrix starts at coordinate index 0, so there is no coordinate below zero
    return False
  if y >= bigheight: # number items on y axis in big matrix. Indexing starts at zero, so number of items -1
    return False
  # the small and big matrix could have the exact same dimensions, 
  # but we are testing if the location + length of the small matrix are outside the bounds of the big matrix
  if x + smallwidth > bigwidth: # x is coordinate being checked + smallwidth must both be inside the bigmatrix and therefore cannot be bigger than bigmarix width.
    return False
  if y + smallheight > bigheight: # y is coordinate being checked + smallheight must both be inside the bigmatrix and therefore cannot be bigger than bigmarix width.
    return False
  
  for dx in range(smallwidth): #for every x axis coordinate in the range within the small matrix. iterate from 0 to small width
    for dy in range(smallheight):  #for every y axis coordinate in the range within the small matrix. iterate from 0 to small height
      if smallmatrix[dx, dy] != bigmatrix[x + dx, y + dy]: #go through each element of the small matrix, 
                                                          #go through each element of big matrix plus offset for coordinate to 
                                                          # see if values match. Coordinate is the guess of where 
                                                          #the top left corner of the little matrix is.
        return False
  return True

#TEST CASES

#2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) #matrix A
# Useful to check size and shape of array for further calculations
# print("number of dimensions: ", A.ndim) 
# print("Shape rows, columns: ", A.shape) 
# print("View number of elements (rows * columns): ", A.size) 
# print("First row A[0] = ", A[0]) 
# print("Second row A[1] = ", A[1]) 

#2 x 2 matrix
B = np.array([[2, 3], [5, 6]]) 
print(B) 

check_matrix_coordinates(B, A)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
Matrix is at:  [0, 1]


##### References
- iterate through 2d and 3d arrays https://www.w3schools.com/python/numpy/numpy_array_iterating.asp
- Numpy searching arrays:  https://www.w3schools.com/python/numpy/numpy_array_search.asp   search for python library that might offer solution