# Question 1:	
You are given a big matrix and a smaller one, write a function that returns the coordinates of a smaller matrix within a bigger one. Start with 2d and experiment with higher dimensions.

In [45]:
import numpy as np 

# find match by row/column index
# iterate through A row 1. return coordinates for matches with B
# Row 2 use same column for row to and confirm match.return coordinates.

# helper function, given an x,y coordinate , it returns true or false whether match.
# given a coordinate, is the smaller matrix at this location
# loop through all coordinates
# 1) loop through all coordinates
# 2) true or false


# HELPER FUNCTION: given an x,y coordinate, look for match and return true or false 
def is_matrix_at_coordinate(coordinate, smallmatrix, bigmatrix):
  #loop starting at coordinate location of each item in the big matrix, compare to item in small matrix & check if items equal
  x = coordinate[0]
  y = coordinate[1]
  smallwidth = smallmatrix.shape[0] 
  smallheight = smallmatrix.shape[1]
  bigwidth = bigmatrix.shape[0] 
  bigheight = bigmatrix.shape[1]

  #MAKE SURE THE SMALL MATRIX COORDINATE OFFSET IS WITHIN DIMENSIONS OF THE BIG MATRIX
  #The first item in the matrix is 0,0 (negatives fall outside the matrix so no need to test there)
  #only test the coordinates within the matrix
  if x < 0: # matrix starts at coordinate index 0, so there is no coordinate below zero
    return False
  if x >= bigwidth: # column or row?
    return False
  if y < 0: # matrix starts at coordinate index 0, so there is no coordinate below zero
    return False
  if y >= bigheight:
    return False
  # the small and big matrix could have the exact same dimensions, 
  # but we are testing if the location + length of the small matrix are outside the bounds of the big matrix
  if x + smallwidth > bigwidth: 
    return False
  if y >= bigheight:
    return False
  
  for dx in range(x, x + smallwidth):
    for dy in range(y, y + smallheight):
      if smallmatrix[x, y] != bigmatrix[dx, dy]:
        return False
  return True

#TEST CASES

#2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) #matrix A
# Useful to check size and shape of array for further calculations
# print("number of dimensions: ", A.ndim) 
# print("Shape rows, columns: ", A.shape) 
# print("View number of elements (rows * columns): ", A.size) 
# print("First row A[0] = ", A[0]) 
# print("Second row A[1] = ", A[1]) 

#2 x 2 matrix
B = np.array([[2, 3], [5, 6]]) 
print(B) 

#coordinates
coordinates = [[-5, -5], [0,0], [0,1], [2,2], [7,7], [1, 1], [100, 10]]

for C in coordinates:
  print(C)
  print(is_matrix_at_coordinate(C, B, A))

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
False


##### References
- iterate through 2d and 3d arrays https://www.w3schools.com/python/numpy/numpy_array_iterating.asp