# Question 3: 
You are given the size of a matrix (e.g. width and height for 2D) and the coordinate of the start and the end of the line segment. Write a function that returns the matrix which has 1 where the line pixels should be and 0 where they shouldn’t. 
Draw the matrix as a graphical output. Start with 2d and experiment with higher dimensions.


- Given: Two dimension of matrix
- Change all values to 1 for those line segment coordinates
- Change the other values to 0

In [3]:
#NOTE TO SELF: CV2 is installed with my Pyhton 3.6
import numpy as np
import skimage 
import skimage.draw

#import skimage.draw import line_aa
#import cv2 
# np.zeros(matrix)
# height = matrix.shape[0]
# width = matrix.shape[1]

def draw_line_segment(shape, start_coordinate, end_coordinate):
  from skimage.draw import line
  img = (np.zeros((shape), dtype=np.uint8))
  rr, cc = line_aa(start_coordinate[0], start_coordinate[1], end_coordinate[0], end_coordinate[1])
  img[rr, cc] = 1
  return img

print(draw_line_segment([10, 10], [1, 1], [8, 8]))

#RUN THIS IN TERMINAL $ ./question4matrix.py

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


## References 
- https://stackoverflow.com/questions/31638651/how-can-i-draw-lines-into-numpy-arrays
- https://scikit-image.org/docs/dev/api/skimage.draw.html#skimage.draw.line_aa 