# Question 2: 
You are given a big matrix, a smaller one and a number representing how much to rotate the smaller matrix in multipliers of π radians in increments of 0.5 (0, 0.5, 1, ...). Write a function that returns a copy of a big matrix where the smaller matrix is rotated  accordingly.

(BigMatrix, SmallMatrix, rotation)
- big matrix
- smaller matrix which needs to be rotated to match big matrix
- rotations 0π, 0.5π, 1π, 1.5π, 2π
0 degrees = 0π
90 =  0.5π
180 = 1π
27 = 1.5π 
360 = 2π

Rotate matrix
- Numpy to find sub matrix
- A function that takes in a matrix to rotate
- only go so far as teh size of the small matrix
- a rotation is a transformation

In [89]:
import numpy as np

#2Dimensionsal
bigMatrix = np.array([[2, 2, 3, 8], [4, 5, 6, 8], [4, 6, 7, 8], [2, 6, 6, 8]])
#print(bigMatrix) 
smallMatrix = np.array([[2, 3, 8], [5, 6, 8]]) 
#print(smallMatrix)
smallMatrix2 = np.array([[6, 8], [7, 8], [6, 8]]) 
#This requires rotation:
bigMatrix3 = np.array([[2, 2, 3, 8], [4, 5, 6, 8], [4, 6, 7, 6], [2, 8, 8, 8]])
smallMatrix3 = np.array([[7, 6], [6, 8]])

#Class from question one 
class MatrixSearch:
  def match_coordinates(smallMatrix, bigMatrix):
    smallMatrix_shape = smallMatrix.shape #returns dimensions of matrix shape row x column for 2D
    # print("SmallMatrix shape is ", smallMatrix_shape)
    width = smallMatrix_shape[0]
    height = smallMatrix_shape[1]
    # print("This is height: ", height)
    # print("This is width: ", width)   
    result = np.where(bigMatrix == smallMatrix[0, 0]) 
    # print(result)
    if result is None:
      return None
    #Finds first coordiante ie match top left corner of small matrix
    for i in range(len(result[0])):
      x = result[0][i] #column
      y = result[1][i] #row
      # print("This is x ", x)
      # print("This is y ", y)
      #This slices the little matrix out of the bigmatrix 
      search_matrix = bigMatrix[x: x + width, y: y + height] 
      print(search_matrix)
      if np.array_equal(smallMatrix, search_matrix):
        match = [x, y]
        print("Match found starting at coordinate: ", match)
        return match #should return all matching coordinates. Stops searching after finding first match.
    return None
  
  def show_all_coordinates(smallMatrix, bigMatrix, match):
    if match is None:
      return None
    smallMatrix_shape = smallMatrix.shape #returns dimensions of matrix shape row x column for 2D
    height = smallMatrix_shape[0]
    width = smallMatrix_shape[1]
    matches = []
    x = match[0]
    y = match[1]
    for dy in range(y, y + height):
      for dx in range(x, x + width):
          matches.append([dx, dy])
    return matches

  #rotate small matrix
  def rotate_matrix(smallMatrix, rotations):
    rotated_matrix = smallMatrix.copy()
    rotated_matrix = np.rot90(rotated_matrix, rotations)
    return rotated_matrix

  def solution(smallMatrix, bigMatrix):
    found = False
    test_matrix = smallMatrix
    for k in range(0, 3):
      if k > 0:
        test_matrix = MatrixSearch.rotate_matrix(test_matrix, k)
      match = MatrixSearch.match_coordinates(test_matrix, bigMatrix)
      if match != None:
        print(MatrixSearch.show_all_coordinates(test_matrix, bigMatrix, match))
        found = True
        break
      if not found:
        print("bigMatrix searched but smallMatrix not found")

  def stars_matches(matches, bigMatrix):
    if matches is None:
      return None
    strmatrix = bigMatrix.astype(str)
    for match in matches:
      strmatrix[match[0]][match[1]] = "*" #just shows where the matching coordinates are - couldn't use a string
      print(strmatrix)
      
#INPUT TO TEST DIFF MATRICES
smallMatrix = smallMatrix3
bigMatrix = bigMatrix3

#Call functions:
print("This is the big matrix: \n", bigMatrix)
print("This is the small matrix: \n", smallMatrix)
match = MatrixSearch.match_coordinates(smallMatrix, bigMatrix)
print("This is the result for match: ", match)
matches = MatrixSearch.show_all_coordinates(smallMatrix, bigMatrix, match)
MatrixSearch.solution(smallMatrix, bigMatrix)
MatrixSearch.stars_matches(matches, bigMatrix)
# print("No rotations: \n", rotate_smallMatrix(smallMatrix, 0))
# print("One rotation: \n", rotate_smallMatrix(smallMatrix, 1))
# print("Two rotations: \n",rotate_smallMatrix(smallMatrix, 2))
# print("Three rotations: \n",rotate_smallMatrix(smallMatrix, 3))


This is the big matrix: 
 [[2 2 3 8]
 [4 5 6 8]
 [4 6 7 6]
 [2 8 8 8]]
This is the small matrix: 
 [[7 6]
 [6 8]]
[[7 6]
 [8 8]]
This is the result for match:  None
[[7 6]
 [8 8]]
bigMatrix searched but smallMatrix not found
[[6 8]
 [7 6]]
Match found starting at coordinate:  [1, 2]
[[1, 2], [2, 2], [1, 3], [2, 3]]


### TO DO:
- The stars_matches function prints the big matrix with stars where the little matrix is found. BUT it does not print when the little matrix has to be rotated to find a match. Fix this.

##### References
- What are radians https://www.youtube.com/watch?v=cgPYLJ-s5II
- https://en.wikipedia.org/wiki/Rotation_matrix#:~:text=Rotation%20matrices%20are%20square%20matrices,1%20and%20det%20R%20%3D%201.
- https://numpy.org/doc/stable/reference/generated/numpy.rot90.html